/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import java.nio.file.Path;
import java.nio.file.Paths;

public class McWalletLib {

    static {
        System.load(getRustLibraryPath().toString());
    }

    private static Path getRustLibraryPath() {
        Path localDirPath = Paths.get(System.getProperty("user.dir"));
        String libRelativePath = "../../mc-wallet-lib-rs/target/release/libmc_wallet_lib_rs.so";
        Path libPath = localDirPath.resolve(libRelativePath);
        return libPath;
    }

    public native int doubleRust(int input);

    public native String createMnemonicRust();

}
