/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import java.nio.file.Path;
import java.nio.file.Paths;

public class McWalletLib {

    static {
        System.load(getRustLibraryPath().toString());
    }

    private static Path getRustLibraryPath() {
        Path localDirPath = Paths.get(System.getProperty("user.dir"));
        String libRelativePath = "../../mc-wallet-lib-rs/target/release/libmc_wallet_lib_rs.so";
        Path libPath = localDirPath.resolve(libRelativePath);
        return libPath;
    }

    public String createWallet(String password) {
        return createWalletRust(password, false);
    }

    public boolean isWalletCreated() {
        return isWalletCreatedRust();
    }

    public String unlockWallet(String password) {
        return unlockWalletRust(password);
    }

    public boolean isWalletUnlocked() {
        return isWalletUnlockedRust();
    }

    native String createWalletRust(String password, boolean test);

    native boolean isWalletCreatedRust();

    native String unlockWalletRust(String password);

    native boolean isWalletUnlockedRust();

}
