/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class McWalletLibTest {

    @Test
    void doubleRust() {
        McWalletLib lib = new McWalletLib();
        assertEquals(4, lib.doubleRust(2));
    }

    @Test
    void createMnemonicRust() {
        McWalletLib lib = new McWalletLib();
        String mnemonic = lib.createMnemonicRust();
        assertNotNull(mnemonic);
        assertTrue(mnemonic.length() > 0);
    }

}
