/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class McWalletLibTest {
    static boolean test = true;

    @Test
    void createWalletRust() {
        McWalletLib lib = new McWalletLib();
        String password = "password";
        String mnemonic = lib.createWalletRust(password, true);
        assertNotNull(mnemonic);
        assertTrue(mnemonic.length() > 0);
    }
}
