/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class McWalletLibTest {
    static boolean test = true;

    @Test
    void testCreateWalletRust() {
        String password = "password";
        String mnemonic = McWalletLib.createWalletRust(password, true);
        assertNotNull(mnemonic);
        assertTrue(mnemonic.length() > 0);
    }

    @Test
    void testCreateAndGetAccountsRust() {
        ArrayList<Account> accounts = McWalletLib.getAccountsRust(true);
        assertNotNull(accounts);
        assertTrue(accounts.size() > 0);
    }
}
