/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.mucks.mc_wallet_lib;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class McWalletLibTest {
    static boolean test = true;

    @Test
    void testCreateWalletRust() {
        String password = "password";
        String mnemonic = McWalletLib.createWalletRust(password, true);
        assertNotNull(mnemonic);
        assertTrue(mnemonic.length() > 0);
    }

    @Test
    void testGetAccountsRust() {
        Account account = McWalletLib.getAccountsRust();

        assertNotNull(account.address);

    }
}
